name: Manic Minter Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  SWANKY_NODE_VER: v1.2.0
  CONTRACTS_NODE: ./swanky-node
  NIGHTLY_VER: nightly-2023-01-10
  CARGO_CONTRACT_VER: 2.1.0
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install & display rust toolchain
        run: |
          rustup show
          rustup toolchain install ${{ env.NIGHTLY_VER }}
          rustup component add rust-src --toolchain ${{ env.NIGHTLY_VER }}-x86_64-unknown-linux-gnu
          rustup component add clippy --toolchain ${{ env.NIGHTLY_VER }}-x86_64-unknown-linux-gnu
          rustup show

      - name: Check targets are installed correctly
        run: rustup target list --installed

      - name: Cargo check
        run: cargo check

      - name: Check Clippy
        run: cargo clippy

  format:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Use cashed cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}

      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Format rust code
        run: cargo fmt --all

  unittest:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Use cashed cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}

      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Format rust code
        run: cargo test

  # integration:
  #   needs: install
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Use cashed cargo
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.cargo
  #         key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}

  #     - name: Checkout the source code
  #       uses: actions/checkout@v3

  #     - name: Check what's installed
  #       run: |
  #         rustup show
  #         rustup target list --installed

  #     - name: Install cargo contract
  #       run: |
  #         cargo install cargo-dylint dylint-link
  #         cargo install cargo-contract --force --version ${{ env.CARGO_CONTRACT_VER }}

  #     - name: download Swanky-node
  #       run: |
  #         sudo wget https://github.com/AstarNetwork/swanky-node/releases/download/${{ env.SWANKY_NODE_VER }}/swanky-node-${{ env.SWANKY_NODE_VER }}-ubuntu-x86_64.tar.gz
  #         sudo tar -zxvf swanky-node-${{ env.SWANKY_NODE_VER }}-ubuntu-x86_64.tar.gz
  #         sudo chmod +x swanky-node
  #         ls -la

  #     - name: e2e test
  #       run: cargo test --features e2e-tests
